runtime: go125
env_variables:
  DOMAIN: "https://vote.aptgg.ee"

automatic_scaling:
  max_instances: 1

handlers:
  - url: /robots.txt
    static_files: static/robots.txt
    upload: static/robots.txt
  - url: /.*
    script: auto
    secure: always
