name: "lint"
on: [push, pull_request]
permissions:
  contents: read
jobs:
  ci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.42.1

      - name: "staticcheck"
        uses: dominikh/staticcheck-action@v1.0.0
        with:
          version: "2021.1.1"